trigger:
  branches:
    include:
      - develop
      - release
      - main
  paths:
    exclude:
      - azure-pipelines.yml

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

variables:
  - name: BRANCH_NAME
    value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
    - group: pragma-lambda-notify-chat-pdn
  - ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/qa') }}:
    - group: pragma-lambda-notify-chat-qa
  - ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    - group: pragma-lambda-notify-chat-dev
  - ${{ else }}:
    - group: pragma-lambda-notify-chat-dev

  - group: notify
resources:
  repositories:     
    - repository: templates
      name: Mapa de crecimiento/pragma-talento-pipelines
      type: git
    - repository: notificacion
      name: Mapa de crecimiento/pragma-talento-pipelines
      type: git
stages:
   - template: lambda-node-sam/lambda_pipeline_template.yml@templates
