AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: pragma-lambda-notify-error - Lambda para la notificación centralizada de errores a sistemas de chat.

Resources:
  PragmaLambdaNotifyError: # CAMBIADO: Nombre lógico de la función
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Timeout: 900 
      MemorySize: 256 
      Tracing: Active
      Environment:
        Variables:
         
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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" # CloudOps gestionará este valor real
          NODE_ENVIRONMENT: "LOCAL" # Esto se sobrescribirá por las variables de Azure DevOps

      Events:
        Api: # CAMBIADO: Nombre lógico del evento API
          Type: Api
          Properties:
            Path: / # CAMBIADO: El path es la raíz para recibir errores
            Method: POST # CAMBIADO: El método para enviar errores es POST

    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        External:
        - reflect-metadata
        - body-parser
        - finalhandler
        
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - app.ts

Outputs:
  # CAMBIADO: Outputs para tu Lambda de Notificación de Errores
  PragmaLambdaNotifyErrorApi:
    Description: API Gateway endpoint URL for Prod stage for PragmaLambdaNotifyError function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  PragmaLambdaNotifyError:
    Description: PragmaLambdaNotifyError Lambda Function ARN
    Value: !GetAtt PragmaLambdaNotifyError.Arn
  PragmaLambdaNotifyErrorIamRole:
    Description: Implicit IAM Role created for PragmaLambdaNotifyError function
    Value: !GetAtt PragmaLambdaNotifyErrorRole.Arn